### ISSUE TITLE
Movement 

### ISSUE THREAD

**Issue by MaxM420** [mergedeyes/your-way-home#1]
Es wäre eigentlich ganz knorke das Movement via Arrowkeys zu realisieren.
Das ganze Geschreibe mit den Himmelsrichtungen wird ziemlich schnell lästig. 

Gruß Maggs <3

**Comment by mergedeyes** [comment]
Das Spiel ist nicht dafür konzipiert einfach durch die Spielwelt zu rennen. Der Spieler wird bewusst ausgebremst um (später hinzukommende) Features aufzunehmen.

**Comment by mergedeyes** [comment]
Wird eventuell dem Spieler überlassen, wie er sich bewegen möchte.

**Comment by MaxM420** [comment]
> Wird eventuell dem Spieler überlassen, wie er sich bewegen möchte.

Das wäre ne super Lösung :]
